// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgeluqCq_iEGjeJhKiEEmdt6OKHcnYVdQ',
    appId: '1:263070899679:web:cd22626cfee4c6a2b2b86a',
    messagingSenderId: '263070899679',
    projectId: 'control-driver-app',
    authDomain: 'control-driver-app.firebaseapp.com',
    storageBucket: 'control-driver-app.firebasestorage.app',
    measurementId: 'G-5QZ6S8R27S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAENMWS6icZFP8MKnRUvEwcJq55iyAv7DY',
    appId: '1:263070899679:android:04be225e02cfb525b2b86a',
    messagingSenderId: '263070899679',
    projectId: 'control-driver-app',
    storageBucket: 'control-driver-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBViLLdTeVpXfUJfmT-Sp3He2deNfbsvYc',
    appId: '1:263070899679:ios:bea09cffcca8fd04b2b86a',
    messagingSenderId: '263070899679',
    projectId: 'control-driver-app',
    storageBucket: 'control-driver-app.firebasestorage.app',
    iosBundleId: 'com.example.controlDriverApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBViLLdTeVpXfUJfmT-Sp3He2deNfbsvYc',
    appId: '1:263070899679:ios:bea09cffcca8fd04b2b86a',
    messagingSenderId: '263070899679',
    projectId: 'control-driver-app',
    storageBucket: 'control-driver-app.firebasestorage.app',
    iosBundleId: 'com.example.controlDriverApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgeluqCq_iEGjeJhKiEEmdt6OKHcnYVdQ',
    appId: '1:263070899679:web:d54ba6274cd810b3b2b86a',
    messagingSenderId: '263070899679',
    projectId: 'control-driver-app',
    authDomain: 'control-driver-app.firebaseapp.com',
    storageBucket: 'control-driver-app.firebasestorage.app',
    measurementId: 'G-4FQ88DNN25',
  );
}
